[project]
name = 'navidrome-scim'
version = "0.1.0"
authors = [
  {name = "Karl Jorgensen", email = "karl@jorgensen.org.uk"},
]
description = "A simple SCIM provider for Navidrome"
requires-python = ">= 3.11"
keywords = ["navidrome", "SCIM"]
dependencies = [
  'Flask >= 2.2',
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
