---
apiVersion: v1
kind: Secret
metadata:
  {{- $secret_name := print (include "navidrome-scim.fullname" .) "-bearer-token" }}
  name: {{ $secret_name }}
  labels:
    {{- include "navidrome-scim.labels" . | nindent 4 }}
type: scim/bearer-token
{{- $existing_secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
data:
  {{- if $existing_secret }}
  token: {{ $existing_secret.data.token }}
  {{- else }}
  # NOTE: `helm diff upgrade` will ALWAYS show a difference here. That is OK.
  token: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
